export const requestData = [
  {
    id: "REQ001",
    user: "Alice Johnson",
    email: "alice@example.com",
    document: "Business_Report_Q4.pdf",
    pages: 25,
    copies: 3,
    status: "pending",
    submittedAt: "12-01-2024 10:30 AM",
    requirements: "Color printing, Double-sided",
  },
  {
    id: "REQ002",
    user: "Bob Smith",
    email: "bob@example.com",
    document: "Marketing_Flyer.pdf",
    pages: 5,
    copies: 100,
    status: "approved",
    submittedAt: "13-01-2024 09:15 AM",
    requirements: "Color printing, High quality",
  },
  {
    id: "REQ003",
    user: "Carol Davis",
    email: "carol@example.com",
    document: "Invoice_Template.pdf",
    pages: 2,
    copies: 50,
    status: "completed",
    submittedAt: "14-01-2024 02:45 PM",
    requirements: "Black & White, Standard quality",
  },
  {
    id: "REQ004",
    user: "David Wilson",
    email: "david@example.com",
    document: "Presentation_Slides.pdf",
    pages: 45,
    copies: 1,
    status: "pending",
    submittedAt: "15-01-2024 11:20 AM",
    requirements: "Color printing, Single-sided",
  },
];
